"""
Pixel Art Sprite Generator for Retro 2D Platformer
Generates 10 smaller enemies and 5 bosses
"""

from PIL import Image, ImageDraw
import os

def create_sprite(width, height, pixel_data, palette):
    """Create a sprite from pixel data and color palette."""
    img = Image.new('RGBA', (width, height), (0, 0, 0, 0))
    pixels = img.load()

    for y, row in enumerate(pixel_data):
        for x, color_idx in enumerate(row):
            if color_idx != ' ' and color_idx in palette:
                pixels[x, y] = palette[color_idx]

    return img

def scale_sprite(img, scale=4):
    """Scale up sprite for better visibility while keeping pixel art look."""
    return img.resize((img.width * scale, img.height * scale), Image.NEAREST)

# ============== SMALLER ENEMIES (32x32) ==============

def create_goblin():
    """Green goblin with a club."""
    palette = {
        'g': (76, 153, 0, 255),      # green skin
        'G': (51, 102, 0, 255),      # dark green
        'e': (255, 0, 0, 255),       # red eyes
        'b': (139, 90, 43, 255),     # brown (club)
        'B': (101, 67, 33, 255),     # dark brown
        'c': (200, 150, 100, 255),   # cloth
        'o': (0, 0, 0, 255),         # outline
    }

    data = [
        "                                ",
        "                                ",
        "                                ",
        "         ooooooooo              ",
        "        oggggggggo              ",
        "       oggggggggggo             ",
        "      ogggggggggggo             ",
        "      ogGgggggggGgo             ",
        "      ogeoggggoego              ",
        "      oggggggggggoo             ",
        "       ogggGGggggooo            ",
        "       ogggggggggo oo           ",
        "        ooggggoo    o           ",
        "         oggggo    oBo          ",
        "        ogcccgo    oBo          ",
        "       ogccccccgo  oBo          ",
        "       ogccccccgo  oBo          ",
        "      ogccgccgccgoBBBo          ",
        "      ogccgccgccgoBBBo          ",
        "       ogcgoogcgo oBo           ",
        "       ogggo  oggo oo           ",
        "        oGGo  oGGo              ",
        "        oGGo  oGGo              ",
        "        oooo  oooo              ",
        "                                ",
        "                                ",
        "                                ",
        "                                ",
        "                                ",
        "                                ",
        "                                ",
        "                                ",
    ]

    return create_sprite(32, 32, data, palette)

def create_gnome():
    """Small gnome with pointy hat."""
    palette = {
        'r': (200, 50, 50, 255),     # red hat
        'R': (150, 30, 30, 255),     # dark red
        's': (255, 200, 150, 255),   # skin
        'S': (220, 170, 130, 255),   # skin shadow
        'b': (100, 80, 60, 255),     # beard (gray-brown)
        'B': (80, 60, 40, 255),      # dark beard
        'c': (70, 130, 70, 255),     # green clothes
        'C': (50, 100, 50, 255),     # dark clothes
        'e': (0, 0, 0, 255),         # eyes
        'o': (40, 30, 20, 255),      # outline
    }

    data = [
        "                                ",
        "                                ",
        "                                ",
        "            ooo                 ",
        "           orrro                ",
        "          orrrrro               ",
        "         orrrrrro               ",
        "        orrrrrrro               ",
        "        orrrrrro                ",
        "       orrrrrro                 ",
        "       ossssso                  ",
        "      osssessso                 ",
        "      osssssssso                ",
        "       osSssSso                 ",
        "       obbbbbbbo                ",
        "      obbbbbbbbbo               ",
        "      obBbbbbBbbo               ",
        "       obbbbbbo                 ",
        "        occccco                 ",
        "       occcccccco               ",
        "       ocCccccCco               ",
        "       occcooccco               ",
        "        occo occo               ",
        "        occo occo               ",
        "        oooo oooo               ",
        "                                ",
        "                                ",
        "                                ",
        "                                ",
        "                                ",
        "                                ",
        "                                ",
    ]

    return create_sprite(32, 32, data, palette)

def create_slime():
    """Classic bouncy slime enemy."""
    palette = {
        'g': (100, 200, 100, 255),   # light green
        'G': (60, 150, 60, 255),     # medium green
        'D': (40, 100, 40, 255),     # dark green
        'h': (150, 230, 150, 255),   # highlight
        'e': (255, 255, 255, 255),   # eye white
        'p': (0, 0, 0, 255),         # pupil
        'o': (30, 80, 30, 255),      # outline
    }

    data = [
        "                                ",
        "                                ",
        "                                ",
        "                                ",
        "                                ",
        "                                ",
        "                                ",
        "                                ",
        "         oooooooo               ",
        "        ohhggggggo              ",
        "       ohggggggggggo            ",
        "      ohgggggggggggo            ",
        "      oggggggggggggo            ",
        "     ogggeoeggeoeggo            ",
        "     ogggepeggepeggo            ",
        "     oGgggggggggggggo           ",
        "     oGGggggggggggggo           ",
        "     oGGGgggggggggGGo           ",
        "      oDGGgggggggGGo            ",
        "      oDDGGGGGGGGGo             ",
        "       oDDDDDDDDDo              ",
        "        ooooooooo               ",
        "                                ",
        "                                ",
        "                                ",
        "                                ",
        "                                ",
        "                                ",
        "                                ",
        "                                ",
        "                                ",
        "                                ",
    ]

    return create_sprite(32, 32, data, palette)

def create_bat():
    """Flying bat enemy."""
    palette = {
        'p': (80, 60, 100, 255),     # purple body
        'P': (60, 40, 80, 255),      # dark purple
        'w': (100, 80, 120, 255),    # wing
        'W': (70, 50, 90, 255),      # dark wing
        'e': (255, 50, 50, 255),     # red eyes
        'f': (200, 150, 150, 255),   # fangs
        'o': (30, 20, 40, 255),      # outline
    }

    data = [
        "                                ",
        "                                ",
        "                                ",
        "                                ",
        "                                ",
        "                                ",
        "                                ",
        " oo                        oo   ",
        " owoo                    oowo   ",
        " owwoo                  oowwo   ",
        "  owwwo      oooo      owwwo    ",
        "  owwwwo   oppppppo   owwwwo    ",
        "   owwwwoopppppppppoowwwwo      ",
        "    owwwwpppeppeppowwwwo        ",
        "     owwwppppppppwwwwo          ",
        "      owwwppffppwwwo            ",
        "       owwwPPPPwwwo             ",
        "        oowwwwwwoo              ",
        "          oooooo                ",
        "                                ",
        "                                ",
        "                                ",
        "                                ",
        "                                ",
        "                                ",
        "                                ",
        "                                ",
        "                                ",
        "                                ",
        "                                ",
        "                                ",
        "                                ",
    ]

    return create_sprite(32, 32, data, palette)

def create_skeleton():
    """Undead skeleton warrior."""
    palette = {
        'w': (240, 240, 230, 255),   # white bone
        'W': (200, 200, 190, 255),   # bone shadow
        'g': (180, 180, 170, 255),   # gray bone
        'e': (50, 0, 0, 255),        # dark eye socket
        'r': (150, 150, 150, 255),   # rib
        'o': (100, 100, 90, 255),    # outline
    }

    data = [
        "                                ",
        "                                ",
        "                                ",
        "          oooooo                ",
        "         owwwwwwo               ",
        "        owwwwwwwwo              ",
        "        oweooweooo              ",
        "        owwwwwwwo               ",
        "        owwooowwo               ",
        "         owwwwwo                ",
        "          oooo                  ",
        "           owo                  ",
        "         oowwwoo                ",
        "        ow owo wo               ",
        "       ow  owo  wo              ",
        "       o  owwwo  o              ",
        "          owwwo                 ",
        "          owwwo                 ",
        "          owowo                 ",
        "          ow wo                 ",
        "          ow wo                 ",
        "          ow wo                 ",
        "          oo oo                 ",
        "         oww wwo                ",
        "          oo oo                 ",
        "                                ",
        "                                ",
        "                                ",
        "                                ",
        "                                ",
        "                                ",
        "                                ",
    ]

    return create_sprite(32, 32, data, palette)

def create_imp():
    """Small flying demon imp."""
    palette = {
        'r': (200, 60, 60, 255),     # red skin
        'R': (150, 40, 40, 255),     # dark red
        'y': (255, 200, 50, 255),    # yellow eyes
        'w': (180, 80, 80, 255),     # wing
        'W': (140, 50, 50, 255),     # dark wing
        'h': (100, 60, 40, 255),     # horn
        't': (200, 80, 80, 255),     # tail
        'o': (80, 30, 30, 255),      # outline
    }

    data = [
        "                                ",
        "                                ",
        "                                ",
        "        oho      oho            ",
        "        ohho    ohho            ",
        "         ohrrrrrho              ",
        "         orrrrrrrro             ",
        "    oo  oryorrryoro  oo         ",
        "   oWo  orrrrrrrro  oWo         ",
        "  oWWo  orrroorrro  oWWo        ",
        "  owwwo orrrrrrro owwwo         ",
        "   owwworRrrrrrRrowwwo          ",
        "    ooo  orrrrro  ooo           ",
        "          oRRRo                 ",
        "          orrro                 ",
        "          orrro                 ",
        "          orooro                ",
        "          oro oro               ",
        "          oo   oo               ",
        "             oto                ",
        "              oto               ",
        "               oo               ",
        "                                ",
        "                                ",
        "                                ",
        "                                ",
        "                                ",
        "                                ",
        "                                ",
        "                                ",
        "                                ",
        "                                ",
    ]

    return create_sprite(32, 32, data, palette)

def create_spider():
    """Creepy spider enemy."""
    palette = {
        'b': (40, 35, 40, 255),      # black body
        'B': (60, 55, 60, 255),      # lighter black
        'r': (200, 50, 50, 255),     # red markings
        'e': (200, 0, 0, 255),       # red eyes
        'l': (50, 45, 50, 255),      # legs
        'o': (20, 15, 20, 255),      # outline
    }

    data = [
        "                                ",
        "                                ",
        "                                ",
        "                                ",
        "                                ",
        "                                ",
        "  o                        o    ",
        "   o                      o     ",
        "   ol                    lo     ",
        "    olo                olo      ",
        "     olo    oooo      olo       ",
        "      olooBBbbBBooolo           ",
        "       oloBbbbbbBolo            ",
        "        oBbebbebBo              ",
        "        oBbbrrbbBo              ",
        "        obbbrrbbbo              ",
        "       olobbbbbolo              ",
        "      olo obbbbo olo            ",
        "     olo   oooo   olo           ",
        "    olo            olo          ",
        "   ol                lo         ",
        "   o                  o         ",
        "  o                    o        ",
        "                                ",
        "                                ",
        "                                ",
        "                                ",
        "                                ",
        "                                ",
        "                                ",
        "                                ",
        "                                ",
    ]

    return create_sprite(32, 32, data, palette)

def create_mushroom():
    """Evil mushroom creature."""
    palette = {
        'r': (220, 80, 80, 255),     # red cap
        'R': (180, 50, 50, 255),     # dark red
        'w': (255, 255, 255, 255),   # white spots
        's': (240, 220, 200, 255),   # stem/face
        'S': (200, 180, 160, 255),   # stem shadow
        'e': (0, 0, 0, 255),         # eyes
        'm': (150, 100, 100, 255),   # mouth
        'f': (180, 160, 140, 255),   # feet
        'o': (100, 50, 50, 255),     # outline
    }

    data = [
        "                                ",
        "                                ",
        "                                ",
        "                                ",
        "         ooooooo                ",
        "        orrrrrrrro              ",
        "       orrwrrrrwrro             ",
        "      orrrrrwwrrrrroo           ",
        "      orrrrrrrrrrrrro           ",
        "     orrwrrrrrrrrrwrro          ",
        "     orrrrrrrrrrrrrrroo         ",
        "      oRRRRRRRRRRRRRo           ",
        "        osssssssso              ",
        "        osseoessso              ",
        "        osssssssso              ",
        "        osssmmssso              ",
        "        oSssssssso              ",
        "        oSssssssso              ",
        "        oSSssssSSo              ",
        "         oossoosso              ",
        "         offo offo              ",
        "         oooo oooo              ",
        "                                ",
        "                                ",
        "                                ",
        "                                ",
        "                                ",
        "                                ",
        "                                ",
        "                                ",
        "                                ",
        "                                ",
    ]

    return create_sprite(32, 32, data, palette)

def create_evil_fairy():
    """Dark fairy enemy."""
    palette = {
        'p': (180, 100, 200, 255),   # purple skin
        'P': (140, 70, 160, 255),    # dark purple
        'w': (200, 180, 220, 255),   # wing
        'W': (160, 140, 180, 255),   # dark wing
        'g': (100, 255, 100, 255),   # glow
        'h': (100, 60, 120, 255),    # hair
        'e': (255, 100, 255, 255),   # pink eyes
        'd': (120, 80, 140, 255),    # dress
        'o': (60, 40, 80, 255),      # outline
    }

    data = [
        "                                ",
        "                                ",
        "                                ",
        "                                ",
        "           ooo                  ",
        "     oo   ohhho   oo            ",
        "    oWo  ohhhho  oWo            ",
        "   oWWo ohhhhhho oWWo           ",
        "   owwo oppepppo owwo           ",
        "   owwooppppppppoowwo           ",
        "   owwo opppppo  owwo           ",
        "    owo  odddo   owo            ",
        "    oo  odddddo  oo             ",
        "       odddddddoo               ",
        "       oddddddddo               ",
        "       oPdddddPo                ",
        "        oddddo                  ",
        "        opooopo                 ",
        "        oo    oo                ",
        "       og      go               ",
        "        o      o                ",
        "                                ",
        "                                ",
        "                                ",
        "                                ",
        "                                ",
        "                                ",
        "                                ",
        "                                ",
        "                                ",
        "                                ",
        "                                ",
    ]

    return create_sprite(32, 32, data, palette)

def create_rat():
    """Giant rat enemy."""
    palette = {
        'b': (120, 100, 90, 255),    # brown fur
        'B': (90, 70, 60, 255),      # dark brown
        'p': (255, 180, 180, 255),   # pink (ears, nose, tail)
        'e': (200, 50, 50, 255),     # red eyes
        'w': (255, 255, 255, 255),   # whiskers/teeth
        't': (200, 150, 150, 255),   # tail
        'o': (50, 40, 35, 255),      # outline
    }

    data = [
        "                                ",
        "                                ",
        "                                ",
        "                                ",
        "                                ",
        "                                ",
        "                                ",
        "                                ",
        "                                ",
        "      opo        opo            ",
        "     oppo  oooo oppo            ",
        "     obboobbbbbobbo             ",
        "    obbbbbbbbbbbbboo            ",
        "   obbbbebbbbbebbbbo            ",
        "  w obbbbbbbbbbbbbbow           ",
        "  w obbbbbbpbbbbbbbo w          ",
        "    obbbbbbbbbbbbbo             ",
        "     oBBbbbbbbbbBo              ",
        "      ooBBBBBBBoo               ",
        "        oooooootoo              ",
        "               otoo             ",
        "                oto             ",
        "                 oo             ",
        "                                ",
        "                                ",
        "                                ",
        "                                ",
        "                                ",
        "                                ",
        "                                ",
        "                                ",
        "                                ",
    ]

    return create_sprite(32, 32, data, palette)

# ============== BOSSES (64x64) ==============

def create_dragon():
    """Fire-breathing dragon boss."""
    palette = {
        'r': (200, 50, 50, 255),     # red scales
        'R': (150, 30, 30, 255),     # dark red
        'D': (100, 20, 20, 255),     # darkest red
        'o': (255, 150, 50, 255),    # orange belly
        'O': (230, 120, 30, 255),    # dark orange
        'y': (255, 255, 100, 255),   # yellow eye
        'w': (180, 60, 60, 255),     # wing
        'W': (140, 40, 40, 255),     # dark wing
        'h': (120, 30, 30, 255),     # horn
        'f': (255, 200, 50, 255),    # fire
        'F': (255, 100, 30, 255),    # dark fire
        'k': (60, 20, 20, 255),      # outline
    }

    data = []
    # Row by row for 64x64 dragon
    template = """
................................................................
................................................................
................................................................
.................khk............................................
................khhhk...........................................
...............khhhhk...........................................
.............kkrrrrrrkk....................kk...................
............krrrrrrrrrrk..................kwwk..................
...........krrrrrrrrrrrk.................kwwwk..................
..........krrrrrrrrrrrrk................kwwwwk..................
.........krrrrrrrrrrrrrk...............kwwwwwk..................
........krrryrrrrrrrrrrrk.............kwwwwwwk..................
.......krrrrrrrrrrrrrrrrrkkkkkkkkkkkkwwwwwwwwk...................
......krrrrrrrrrrrrrrrrrrrrrrrrrrrrrwwwwwwwwk....................
.....krrrrrrrrRrrrrrrrrrrrrrrrrrrrrwwwwwwwwk.....................
....krrrrrrrrrrrrrrrrrrrrrrrrrrrrRwwwwwwwwk......................
....krrrRrrrrrrrrrrrrrrrrrrrrrrrrwwwwwwwwk.......................
...krrrrrrrrrrrrrrrrrRrrrrrrrrrRwwwwwwwwk........................
...krrrrrrrrrrrrrrrrrrrrrrrrrrrwwwwwwwk..........................
..krrrrrrrrrrrrrrrrrrrrrrrrrRrwwwwwwk............................
..krrrrrrrrrrrrrrrrrrrrrrrrrwwwwwwk..............................
..krrrroooooorrrrrrrrrrrrrrrwwwwk................................
..krrroooooooorrrrrrrrrrrrrwwwk..................................
..krrrooooooooorrrrrrrrrrrwwk...................................
..krrooOOOoooooorrrrrrrrrrk.....................................
..kroooOOOoooooorrrrrrrrk.......................................
..kroooOOooooooorrrrrrrk........................................
..kroooooooooooorrrrrrk.........................................
..krooooooooooorrrrrrrk.........................................
...krooooooooorrrrrrrrk.........................................
...krroooooorrrrrrrrrrk.........................................
....krrroorrrrrrrrrrrrk.........................................
....krrrrrrrrrrrrrRrrk..........................................
.....krrrrrrrrrrrrrrk...........................................
......krrrrRrrrrrrrrk...........................................
.......krrrrrrrrrRrrk...........................................
........krrrrrrrrrrk............................................
.........krrrrrrrrk.............................................
..........krRrrrrk..............................................
...........krrrrk...............................................
............krrk................................................
.............kk.................................................
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
"""

    for line in template.strip().split('\n'):
        data.append(line)

    return create_sprite(64, 64, data, palette)

def create_minotaur():
    """Powerful minotaur boss with axe."""
    palette = {
        'b': (139, 90, 60, 255),     # brown fur
        'B': (100, 60, 40, 255),     # dark brown
        's': (180, 130, 100, 255),   # skin/snout
        'h': (80, 50, 30, 255),      # horns
        'H': (60, 35, 20, 255),      # dark horn
        'e': (255, 50, 50, 255),     # red eyes
        'n': (50, 30, 20, 255),      # nose ring
        'a': (150, 150, 160, 255),   # axe blade
        'A': (120, 120, 130, 255),   # dark axe
        'w': (100, 70, 50, 255),     # wood handle
        'p': (80, 60, 50, 255),      # pants
        'P': (60, 40, 30, 255),      # dark pants
        'k': (40, 25, 15, 255),      # outline
    }

    data = []
    template = """
................................................................
................................................................
................................................................
..........khhhk..............................khhhhk..............
.........khhhhhhk..........................khhhhhhhk.............
........khhhhhhhhk........................khhhhhhhhk.............
.......kHhhhhhhhhhkkkkkkkkkkkkkkkkkkkkkkkkhhhhhhhhhHk.............
........khhhhhhhhbbbbbbbbbbbbbbbbbbbbbbbbhhhhhhhhk...............
.........khhhhkbbbbbbbbbbbbbbbbbbbbbbbbbbbbkhhhhk................
..........kkkkbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbkkkk.................
............kbbbbbbbebbbbbbbbbbbbbbbebbbbbbk.....................
...........kbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbk.....................
...........kbbbbbbbbbbbbssssssbbbbbbbbbbbbk......................
..........kbbbbbbbbbbbbssssssssbbbbbbbbbbbk......................
..........kbbbbbbbbbbbbbssnsssbbbbbbbbbbbbk......................
..........kbbbbbbbbbbbbbbssssbbbbbbbbbbbbk.......................
...........kbbbbbbbbbbbbbbbbbbbbbbbbbbbbk........................
...........kbbbbkkkkkbbbbbbbbbbkkkkkbbbk.........................
...........kbbkwkaaakbbbbbbbbbkwkaaakbbk.........................
..........kbbkwwkaaakbbbbbbbbkwwkaaakbbk.........................
..........kbbkwwwkakbbbbbbbbbkwwwkakbbbk.........................
.........kbbbkwwwkkbbbbbbbbbbkwwwkkbbbk..........................
.........kbbbkwwwkBBBBBBBBBBBkwwwkbbbbk..........................
........kbbbbkwwwkBBBBBBBBBBBkwwwkbbbk...........................
........kbbbbbkwkBBBBBBBBBBBBBkwkbbbk............................
.......kbbbbbbbkBBBBBBBBBBBBBBBkbbbk.............................
.......kbbbbbbbbBBBBBBBBBBBBBBBbbbk..............................
......kbbbbbbbbbBBBBBBBBBBBBBBbbbbk..............................
......kbbbbbbbbbBBBBBBBBBBBBBbbbbbk..............................
.....kbbbbbbbbbbpppppppppppppbbbbbk..............................
.....kbbbbbbbbbppppppppppppppbbbbk...............................
....kbbbbbbbbbbpppppppppppppppbbbk...............................
....kbbbbbbbbbpppppPPPPPpppppbbbbk...............................
...kbbbbbbbbbbppppPPPPPPppppbbbbbk...............................
...kbbbbbbbbbpppppPPPPPPpppppbbbbk...............................
..kbbbbbbbbbbppppPPPPPPPPppppbbbk................................
..kbbbbbbbbbpppppPP..PPPPpppbbbbk................................
..kbbbbbbbbpppppPP....PPPPppbbbk.................................
..kbbbbbbbpppppPP......PPPppbbk..................................
..kbbbbbbppppPP..........PPpbk...................................
...kbbbbbpppP..............kk....................................
...kbbbbppP......................................................
....kbbbpk.......................................................
....kbbkk........................................................
.....kk..........................................................
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
"""

    for line in template.strip().split('\n'):
        data.append(line)

    return create_sprite(64, 64, data, palette)

def create_cyclops():
    """Giant one-eyed cyclops boss."""
    palette = {
        's': (180, 160, 140, 255),   # skin
        'S': (140, 120, 100, 255),   # skin shadow
        'e': (255, 255, 200, 255),   # eye white
        'p': (50, 50, 50, 255),      # pupil
        'E': (200, 200, 150, 255),   # eye shadow
        'b': (120, 90, 70, 255),     # brown cloth
        'B': (90, 60, 40, 255),      # dark cloth
        't': (200, 180, 160, 255),   # teeth
        'c': (100, 80, 60, 255),     # club
        'C': (70, 50, 30, 255),      # dark club
        'k': (60, 50, 40, 255),      # outline
    }

    data = []
    template = """
................................................................
................................................................
................................................................
................................................................
................................................................
..............kkkkkkkkkkkkkkkkkkkkkk.............................
............kkssssssssssssssssssssskk...........................
...........kssssssssssssssssssssssssk...........................
..........kssssssssssssssssssssssssssk..........................
.........ksssssssssssssssssssssssssssk..........................
........ksssssssssssssssssssssssssssssk.........................
.......kssssssssssskkkkkkkkkssssssssssk.........................
......ksssssssssskkeeeeeeeeekkssssssssk.........................
......kssssssssskeeeeeeeeeeeeeksssssssk.........................
.....kssssssssskeeeeeeppeeeeeeekssssssk.........................
.....ksssssssskeeeeeeepppeeeeeeksssssssk........................
....kssssssssskeeeeeepppeeeeeeeksssssssk........................
....kssssssssskEeeeeeeeeeeeeeEekssssssk.........................
....ksssssssssskkEEeeeeeeeEEkkssssssssk.........................
...kssssssssssssskkkkkkkkkksssssssssssk.........................
...ksssssssssssssssssssssssssssssssssk..........................
...kssssssssssssssssssssssssssssssssk...........................
...kssssSsssssssssttttttsssssssssSssk...........................
...ksssssSsssssssssssssssssssssSsssk............................
....ksssssSssssssSSSSSSSssssssSssssk............................
....kssssssSSSSSSSSSSSSSSSSSSSsssssk............................
.....ksssssssssSSSSSSSSSSssssssssssk............................
.....ksssssssssssssssssssssssssssk..............................
......kssssskkkssssssssssskkkssk................................
......kssssskcckssssssssskcckssk................................
.......kssskccckbbbbbbbbbkcccksk................................
........kkkcccckbbbbbbbbbkccckk.................................
.........kcccccckbbbbbbbkccccck.................................
.........kcccccckBBBBBBBkccccck.................................
..........kccccckBBBBBBBkccccck.................................
..........kccccckBBBBBBBkccccck.................................
...........kccckBBBBBBBBBkcccck.................................
...........kcckBBBBBBBBBBBkccck.................................
............kckbbbBBBbbbbbkCCk..................................
............kckbbbbbbbbbbbkCk...................................
.............kkbbbbbbbbbbbkk....................................
..............kbbbbbbbbbbbk.....................................
..............kbbbbbbbbbbbk.....................................
..............kbbbb..bbbbbk.....................................
..............kbbb....bbbbk.....................................
...............kbb....bbbk......................................
...............kb......bbk......................................
................k......kk.......................................
................k......k........................................
.................k....k.........................................
.................kk..kk.........................................
..................kkkk..........................................
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
"""

    for line in template.strip().split('\n'):
        data.append(line)

    return create_sprite(64, 64, data, palette)

def create_dark_wizard():
    """Evil dark wizard boss."""
    palette = {
        'p': (60, 40, 80, 255),      # purple robe
        'P': (40, 25, 55, 255),      # dark purple
        's': (200, 180, 160, 255),   # skin
        'S': (160, 140, 120, 255),   # skin shadow
        'b': (30, 20, 40, 255),      # black
        'e': (200, 50, 255, 255),    # glowing eyes
        'g': (150, 50, 200, 255),    # magic glow
        'G': (200, 100, 255, 255),   # bright glow
        'w': (120, 90, 60, 255),     # staff wood
        'W': (90, 60, 40, 255),      # dark wood
        'o': (180, 120, 255, 255),   # orb
        'h': (150, 150, 160, 255),   # hair/beard
        'H': (120, 120, 130, 255),   # dark hair
        'k': (20, 10, 30, 255),      # outline
    }

    data = []
    template = """
................................................................
................................................................
................................................................
..............kkkkkkk...........................................
.............kbbbbbbbk..........................................
............kbbbbbbbbbk..........................k..............
...........kbbbbbbbbbbk.........................kwk.............
..........kbbbbbbbbbbbk........................kwwk.............
..........kbbbbbbbbbbk........................kwwwk.............
.........kbbbbbbbbbbk........................kwwwwk.............
.........kbbbbbbbbbk........................kwwwwwk.............
........kbbbbbbbbbk........................kwwwwwwk.............
........kbbbbbbbbk........................kwwwwwwwk.............
.......kbbbbbbbbk........................kooooowwwk.............
.......kpppppppk........................koGGGGowwwk.............
......kpppppppk.........................koGGGGowwwk.............
......kppsssspk.........................koGGGGowwwk.............
.....kppseesepk..........................kooookwwk..............
.....kppssssspk............................kwwwwk...............
.....kpphhhhhpk............................kwwwwk...............
....kpphhhhhhppk...........................kwwwwk...............
....kpphHHHHhppk...........................kwwwwk...............
....kpphhhhhhpk............................kwwwwk...............
...kppppppppppk............................kwwwwk...............
...kpppppPpppppk...........................kwwwwk...............
..kppppppPppppppk..........................kwwwwk...............
..kpppppPPPpppppk..........................kwwwwk...............
..kppppPPPPppppppk.........................kwwwwk...............
.kpppppPPPPpppppppk........................kwwwwk...............
.kppppPPPPPPppppppk........................kwwwwk...............
kpppppPPPPPPpppppppk.......................kwwwwk...............
kppppPPPPPPPPppppppk.......................kwwwwk...............
kpppppPPPPPPppppppppk......................kwwwwk...............
kppppppPPPPpppppppppk......................kwwwwk...............
kpppppppPPppppppppppk......................kwwwk................
.kpppppppppppppppppk.......................kwwk.................
.kppppppppppppppppppk......................kwk..................
..kpppppppppppppppppk......................kk...................
..kppppppppppppppppk........................................
...kpppppppppppppppk........................................
...kppppppp.ppppppk.........................................
....kpppppp.pppppk..........................................
....kppppp...ppppk..........................................
.....kpppp...pppk...........................................
.....kppp.....ppk...........................................
......kpp.....pk............................................
......kp.......k............................................
.......k......k.............................................
.......k......k.............................................
........k....k..............................................
........kk..kk..............................................
.........kkkk...............................................
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
"""

    for line in template.strip().split('\n'):
        data.append(line)

    return create_sprite(64, 64, data, palette)

def create_demon_lord():
    """Ultimate demon lord boss."""
    palette = {
        'r': (180, 40, 40, 255),     # red skin
        'R': (130, 25, 25, 255),     # dark red
        'D': (90, 15, 15, 255),      # darkest red
        'h': (50, 30, 30, 255),      # horns
        'H': (30, 15, 15, 255),      # dark horns
        'e': (255, 200, 50, 255),    # yellow eyes
        'f': (255, 150, 50, 255),    # fire/glow
        'F': (255, 100, 30, 255),    # dark fire
        'w': (100, 30, 30, 255),     # wings
        'W': (70, 20, 20, 255),      # dark wings
        'b': (40, 20, 20, 255),      # black
        't': (200, 200, 200, 255),   # teeth
        'a': (150, 150, 160, 255),   # armor
        'A': (100, 100, 110, 255),   # dark armor
        'k': (30, 10, 10, 255),      # outline
    }

    data = []
    template = """
................................................................
..........khhk....................................khhk...........
.........khhhk..................................khhhk...........
........khhhhk................................khhhhk............
.......khhhhhk..............................khhhhhhk............
......khhhhhhk.............................khhhhhhhk............
.....khhhhhhhkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkhhhhhhhhk.............
....khhhhhhhrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrhhhhhhhhk.............
...khhhhhkrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrkhhhhhk..............
..kkkkkkrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrkkkkk...............
..kwwkrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrkwwk...............
.kwwwkrrrrrrrerrrrrrrrrrrrrrrrrrrrrrrrerrrrrrrkwwwk..............
.kwwwkrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrkwwwwk..............
kwwwwkrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrkwwwwk.............
kwwwwkrrrrrrrrrrrrrttttttttttrrrrrrrrrrrrrrrrrkwwwwk.............
kwwwwkrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrkwwwwk.............
kwwwwkRrrrrrrrrrrRRRRRRRRRRRRRRrrrrrrrrrrrRrrkwwwwk..............
kwwwwkRRrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrRRrkwwwwwk..............
kwwwwkRRRrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrRRRrkkwwwwwk..............
kwwwwkkRRRrrrrrrrrrrrrrrrrrrrrrrrrrrrrRRRkkwwwwwwk...............
kwwwwwwkRRRRrrrrrrrrrrrrrrrrrrrrrrrRRRRkkwwwwwwwk................
.kwwwwwwkkRRRRRrrrrrrrrrrrrrrrrRRRRRkkwwwwwwwwwk.................
..kwwwwwwwkkRRRRRRRrrrrrrrrRRRRRRkkwwwwwwwwwwwk..................
...kwwwwwwwwkkkaaaaaaaaaaaaaaaakkwwwwwwwwwwwk....................
....kwwwwwwwkkaaaAAAAAAAAAAAAaaakwwwwwwwwwk......................
.....kwwwwwkkaaAAAAAAAAAAAAAAAAaakwwwwwwk........................
......kwwwkkaAAAAAAAAAAAAAAAAAAAAAkkwwwk.........................
.......kkkkaaAAAAAAAAAAAAAAAAAAAAAAkkk...........................
..........kaaAAAAAAAAAAAAAAAAAAAAaaak............................
..........kaaaaAAAAAAAAAAAAAAAAAAaaak............................
.........kaaaaaaAAAAAAAAAAAAAAaaaaaak............................
.........kaaaaaaaAAAAAAAAAAAAaaaaaaak............................
........kaaaaaaaaAAA....AAAaaaaaaaaaak...........................
........kaaaaaaaaaA......Aaaaaaaaaaak............................
.......kaaaaaaaaaaA......Aaaaaaaaaaak............................
.......kaaaaaaaaaa........aaaaaaaaaak............................
......kaaaaaaaaaa..........aaaaaaaaaak...........................
......kaaaaaaaa..............aaaaaaak............................
.....kaaaaaaaa................aaaaaaak...........................
.....kaaaaaaa..................aaaaaaak..........................
....kaaaaaaa....................aaaaaaak.........................
....kaaaaaa......................aaaaaaak........................
...kaaaaaaa......................aaaaaaak........................
...kaaaaaak......................kaaaaak.........................
...kaaaaak........................kaaaak.........................
....kakak..........................kkak..........................
....kkkkk..........................kkkk..........................
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
"""

    for line in template.strip().split('\n'):
        data.append(line)

    return create_sprite(64, 64, data, palette)

def main():
    # Ensure directories exist
    os.makedirs('assets/enemies', exist_ok=True)
    os.makedirs('assets/bosses', exist_ok=True)

    # Create and save smaller enemies
    enemies = [
        ('goblin', create_goblin),
        ('gnome', create_gnome),
        ('slime', create_slime),
        ('bat', create_bat),
        ('skeleton', create_skeleton),
        ('imp', create_imp),
        ('spider', create_spider),
        ('mushroom', create_mushroom),
        ('evil_fairy', create_evil_fairy),
        ('rat', create_rat),
    ]

    print("Generating smaller enemies (32x32, scaled to 128x128)...")
    for name, create_func in enemies:
        sprite = create_func()
        scaled = scale_sprite(sprite, 4)
        scaled.save(f'assets/enemies/{name}.png')
        print(f"  Created: {name}.png")

    # Create and save bosses
    bosses = [
        ('dragon', create_dragon),
        ('minotaur', create_minotaur),
        ('cyclops', create_cyclops),
        ('dark_wizard', create_dark_wizard),
        ('demon_lord', create_demon_lord),
    ]

    print("\nGenerating bosses (64x64, scaled to 256x256)...")
    for name, create_func in bosses:
        sprite = create_func()
        scaled = scale_sprite(sprite, 4)
        scaled.save(f'assets/bosses/{name}.png')
        print(f"  Created: {name}.png")

    print("\nAll sprites generated successfully!")
    print(f"\nEnemy sprites saved to: assets/enemies/")
    print(f"Boss sprites saved to: assets/bosses/")

if __name__ == '__main__':
    main()
